# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(24, 20, 24, 20)
        self.verticalLayout.setSpacing(14)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.lbl_student = QtWidgets.QLabel(self.centralwidget)
        self.lbl_student.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_student.setObjectName("lbl_student")
        self.verticalLayout.addWidget(self.lbl_student)
        self.lbl_plain_text = QtWidgets.QLabel(self.centralwidget)
        self.lbl_plain_text.setObjectName("lbl_plain_text")
        self.verticalLayout.addWidget(self.lbl_plain_text)
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setAcceptRichText(False)
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.verticalLayout.addWidget(self.txt_plain_text)
        self.keyLayout = QtWidgets.QHBoxLayout()
        self.keyLayout.setObjectName("keyLayout")
        self.lbl_key = QtWidgets.QLabel(self.centralwidget)
        self.lbl_key.setObjectName("lbl_key")
        self.keyLayout.addWidget(self.lbl_key)
        self.txt_key = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_key.setObjectName("txt_key")
        self.keyLayout.addWidget(self.txt_key)
        self.verticalLayout.addLayout(self.keyLayout)
        self.lbl_cipher_text = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cipher_text.setObjectName("lbl_cipher_text")
        self.verticalLayout.addWidget(self.lbl_cipher_text)
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setAcceptRichText(False)
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.verticalLayout.addWidget(self.txt_cipher_text)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.buttonLayout.addWidget(self.btn_encrypt)
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.buttonLayout.addWidget(self.btn_decrypt)
        self.verticalLayout.addLayout(self.buttonLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txt_plain_text, self.txt_key)
        MainWindow.setTabOrder(self.txt_key, self.txt_cipher_text)
        MainWindow.setTabOrder(self.txt_cipher_text, self.btn_encrypt)
        MainWindow.setTabOrder(self.btn_encrypt, self.btn_decrypt)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Caesar Cipher - LeHoangHuy_2410060274"))
        self.lbl_title.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.lbl_student.setText(_translate("MainWindow", "Lê Hoàng Huy - 2410060274"))
        self.lbl_plain_text.setText(_translate("MainWindow", "Bản rõ (Plain text):"))
        self.txt_plain_text.setPlaceholderText(_translate("MainWindow", "Nhập nội dung cần mã hóa..."))
        self.lbl_key.setText(_translate("MainWindow", "Khóa dịch (Key):"))
        self.txt_key.setText(_translate("MainWindow", "3"))
        self.txt_key.setPlaceholderText(_translate("MainWindow", "Nhập số nguyên, ví dụ: 3"))
        self.lbl_cipher_text.setText(_translate("MainWindow", "Bản mã (Cipher text):"))
        self.txt_cipher_text.setPlaceholderText(_translate("MainWindow", "Kết quả mã hóa hoặc nội dung cần giải mã..."))
        self.btn_encrypt.setText(_translate("MainWindow", "Mã hóa (Encrypt)"))
        self.btn_decrypt.setText(_translate("MainWindow", "Giải mã (Decrypt)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
