# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.lbl_student = QtWidgets.QLabel(self.centralwidget)
        self.lbl_student.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_student.setObjectName("lbl_student")
        self.verticalLayout.addWidget(self.lbl_student)
        self.lbl_plain = QtWidgets.QLabel(self.centralwidget)
        self.lbl_plain.setObjectName("lbl_plain")
        self.verticalLayout.addWidget(self.lbl_plain)
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.verticalLayout.addWidget(self.txt_plain_text)
        self.keyLayout = QtWidgets.QHBoxLayout()
        self.keyLayout.setObjectName("keyLayout")
        self.lbl_key = QtWidgets.QLabel(self.centralwidget)
        self.lbl_key.setObjectName("lbl_key")
        self.keyLayout.addWidget(self.lbl_key)
        self.txt_key = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_key.setObjectName("txt_key")
        self.keyLayout.addWidget(self.txt_key)
        self.verticalLayout.addLayout(self.keyLayout)
        self.lbl_cipher = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cipher.setObjectName("lbl_cipher")
        self.verticalLayout.addWidget(self.lbl_cipher)
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.verticalLayout.addWidget(self.txt_cipher_text)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.buttonLayout.addWidget(self.btn_encrypt)
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.buttonLayout.addWidget(self.btn_decrypt)
        self.verticalLayout.addLayout(self.buttonLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Playfair Cipher - LeHoangHuy_2410060274"))
        self.lbl_title.setStyleSheet(_translate("MainWindow", "font-size: 26px; font-weight: bold;"))
        self.lbl_title.setText(_translate("MainWindow", "PLAYFAIR CIPHER"))
        self.lbl_student.setText(_translate("MainWindow", "Lê Hoàng Huy - 2410060274"))
        self.lbl_plain.setText(_translate("MainWindow", "Bản rõ (Plain text):"))
        self.lbl_key.setText(_translate("MainWindow", "Khóa (Key):"))
        self.txt_key.setText(_translate("MainWindow", "SECURITY"))
        self.lbl_cipher.setText(_translate("MainWindow", "Bản mã (Cipher text):"))
        self.btn_encrypt.setText(_translate("MainWindow", "Mã hóa (Encrypt)"))
        self.btn_decrypt.setText(_translate("MainWindow", "Giải mã (Decrypt)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
