# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.main_layout.setContentsMargins(28, 24, 28, 20)
        self.main_layout.setSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.lbl_badge = QtWidgets.QLabel(self.centralwidget)
        self.lbl_badge.setObjectName("lbl_badge")
        self.main_layout.addWidget(self.lbl_badge)
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setObjectName("lbl_title")
        self.main_layout.addWidget(self.lbl_title)
        self.lbl_subtitle = QtWidgets.QLabel(self.centralwidget)
        self.lbl_subtitle.setObjectName("lbl_subtitle")
        self.main_layout.addWidget(self.lbl_subtitle)
        self.keys_layout = QtWidgets.QHBoxLayout()
        self.keys_layout.setObjectName("keys_layout")
        self.lbl_keys = QtWidgets.QLabel(self.centralwidget)
        self.lbl_keys.setObjectName("lbl_keys")
        self.keys_layout.addWidget(self.lbl_keys)
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.keys_layout.addWidget(self.btn_gen_keys)
        self.main_layout.addLayout(self.keys_layout)
        self.messages_layout = QtWidgets.QHBoxLayout()
        self.messages_layout.setObjectName("messages_layout")
        self.group_plain = QtWidgets.QGroupBox(self.centralwidget)
        self.group_plain.setObjectName("group_plain")
        self.group_plain_layout = QtWidgets.QVBoxLayout(self.group_plain)
        self.group_plain_layout.setObjectName("group_plain_layout")
        self.txt_plain_text = QtWidgets.QTextEdit(self.group_plain)
        self.txt_plain_text.setAcceptRichText(False)
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.group_plain_layout.addWidget(self.txt_plain_text)
        self.messages_layout.addWidget(self.group_plain)
        self.group_cipher = QtWidgets.QGroupBox(self.centralwidget)
        self.group_cipher.setObjectName("group_cipher")
        self.group_cipher_layout = QtWidgets.QVBoxLayout(self.group_cipher)
        self.group_cipher_layout.setObjectName("group_cipher_layout")
        self.txt_cipher_text = QtWidgets.QTextEdit(self.group_cipher)
        self.txt_cipher_text.setAcceptRichText(False)
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.group_cipher_layout.addWidget(self.txt_cipher_text)
        self.messages_layout.addWidget(self.group_cipher)
        self.main_layout.addLayout(self.messages_layout)
        self.cipher_buttons = QtWidgets.QHBoxLayout()
        self.cipher_buttons.setObjectName("cipher_buttons")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.cipher_buttons.addWidget(self.btn_encrypt)
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.cipher_buttons.addWidget(self.btn_decrypt)
        self.main_layout.addLayout(self.cipher_buttons)
        self.group_signature = QtWidgets.QGroupBox(self.centralwidget)
        self.group_signature.setObjectName("group_signature")
        self.signature_layout = QtWidgets.QVBoxLayout(self.group_signature)
        self.signature_layout.setObjectName("signature_layout")
        self.lbl_sign_help = QtWidgets.QLabel(self.group_signature)
        self.lbl_sign_help.setObjectName("lbl_sign_help")
        self.signature_layout.addWidget(self.lbl_sign_help)
        self.txt_info = QtWidgets.QTextEdit(self.group_signature)
        self.txt_info.setAcceptRichText(False)
        self.txt_info.setObjectName("txt_info")
        self.signature_layout.addWidget(self.txt_info)
        self.lbl_signature = QtWidgets.QLabel(self.group_signature)
        self.lbl_signature.setObjectName("lbl_signature")
        self.signature_layout.addWidget(self.lbl_signature)
        self.txt_sign = QtWidgets.QTextEdit(self.group_signature)
        self.txt_sign.setAcceptRichText(False)
        self.txt_sign.setObjectName("txt_sign")
        self.signature_layout.addWidget(self.txt_sign)
        self.signature_buttons = QtWidgets.QHBoxLayout()
        self.signature_buttons.setObjectName("signature_buttons")
        self.btn_sign = QtWidgets.QPushButton(self.group_signature)
        self.btn_sign.setObjectName("btn_sign")
        self.signature_buttons.addWidget(self.btn_sign)
        self.btn_verify = QtWidgets.QPushButton(self.group_signature)
        self.btn_verify.setObjectName("btn_verify")
        self.signature_buttons.addWidget(self.btn_verify)
        self.signature_layout.addLayout(self.signature_buttons)
        self.main_layout.addWidget(self.group_signature)
        self.lbl_footer = QtWidgets.QLabel(self.centralwidget)
        self.lbl_footer.setObjectName("lbl_footer")
        self.main_layout.addWidget(self.lbl_footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_gen_keys, self.txt_plain_text)
        MainWindow.setTabOrder(self.txt_plain_text, self.txt_cipher_text)
        MainWindow.setTabOrder(self.txt_cipher_text, self.btn_encrypt)
        MainWindow.setTabOrder(self.btn_encrypt, self.btn_decrypt)
        MainWindow.setTabOrder(self.btn_decrypt, self.txt_info)
        MainWindow.setTabOrder(self.txt_info, self.txt_sign)
        MainWindow.setTabOrder(self.txt_sign, self.btn_sign)
        MainWindow.setTabOrder(self.btn_sign, self.btn_verify)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA Cipher | Lê Hoàng Huy - 2410060274"))
        MainWindow.setStyleSheet(_translate("MainWindow", "QMainWindow { background: #f3f6fb; }\n"
"QWidget { font-family: \"Segoe UI\"; font-size: 14px; color: #23344d; }\n"
"QLabel#lbl_title { font-size: 28px; font-weight: 700; color: #122746; }\n"
"QLabel#lbl_subtitle, QLabel#lbl_footer { color: #687a92; font-size: 12px; }\n"
"QLabel#lbl_badge { color: #2563eb; font-weight: 600; }\n"
"QGroupBox { background: white; border: 1px solid #dce4ef; border-radius: 12px; margin-top: 16px; padding: 20px 16px 14px; font-weight: 600; }\n"
"QGroupBox::title { subcontrol-origin: margin; left: 18px; padding: 0 6px; }\n"
"QTextEdit, QLineEdit { background: #f9fbfe; border: 1px solid #d4deeb; border-radius: 7px; padding: 10px; font-weight: 400; selection-background-color: #2563eb; }\n"
"QTextEdit:focus, QLineEdit:focus { border: 1px solid #2563eb; }\n"
"QPushButton { background: #2563eb; color: white; border: none; border-radius: 7px; padding: 12px 24px; font-weight: 600; }\n"
"QPushButton:hover { background: #1d4ed8; }\n"
"QPushButton:pressed { background: #1e40af; }\n"
"QPushButton#btn_decrypt { background: #e8eef9; color: #234a83; }\n"
"QPushButton#btn_decrypt:hover { background: #dbe6f8; }\n"
"\n"
"QPushButton#btn_gen_keys { background: #122746; }\n"
"QPushButton#btn_verify { background: #e8eef9; color: #234a83; }\n"
"QTextEdit#txt_info { background: #edf3fb; }"))
        self.lbl_badge.setText(_translate("MainWindow", "BÀI 3.5.2  /  MẬT MÃ KHÓA CÔNG KHAI"))
        self.lbl_title.setText(_translate("MainWindow", "RSA CIPHER"))
        self.lbl_subtitle.setText(_translate("MainWindow", "Mã hóa, giải mã và chữ ký số • PyQt5 + Flask API"))
        self.lbl_keys.setText(_translate("MainWindow", "01   Tạo cặp khóa trước khi thực hiện các chức năng"))
        self.btn_gen_keys.setText(_translate("MainWindow", "Tạo khóa / Generate Keys"))
        self.group_plain.setTitle(_translate("MainWindow", "02   Bản rõ / Plain Text"))
        self.txt_plain_text.setPlaceholderText(_translate("MainWindow", "Nhập nội dung cần mã hóa…"))
        self.group_cipher.setTitle(_translate("MainWindow", "03   Bản mã / Cipher Text"))
        self.txt_cipher_text.setPlaceholderText(_translate("MainWindow", "Bản mã RSA dạng hex…"))
        self.btn_encrypt.setText(_translate("MainWindow", "Mã hóa / Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Giải mã / Decrypt"))
        self.group_signature.setTitle(_translate("MainWindow", "04   Chữ ký số"))
        self.lbl_sign_help.setText(_translate("MainWindow", "Thông điệp dùng để ký và xác minh"))
        self.txt_info.setPlaceholderText(_translate("MainWindow", "Nhập thông điệp cần ký hoặc xác minh…"))
        self.lbl_signature.setText(_translate("MainWindow", "Chữ ký / Signature (hex)"))
        self.txt_sign.setPlaceholderText(_translate("MainWindow", "Chữ ký được tạo hoặc chữ ký cần xác minh…"))
        self.btn_sign.setText(_translate("MainWindow", "Ký thông điệp / Sign"))
        self.btn_verify.setText(_translate("MainWindow", "Xác minh / Verify"))
        self.lbl_footer.setText(_translate("MainWindow", "Lê Hoàng Huy  •  MSHV: 2410060274"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
